import MdView from "@/components/MdView";
import { Metadata } from "next/types";

export default function Home() {
  return (
    <>
      <div className="max-w-3xl mx-auto my-14">
        <MdView />
      </div>
    </>
  );
}


export const metadata: Metadata = {
  title: "Social Media or Messaging API",
  description: "Generated by create next app",
}

